# Spam Classifier
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
Spam refers to unwanted email, often in the form of advertisements. In the literature, an email that is **not** spam is called *ham*. Most email providers offer automatic spam filtering, where spam emails will be moved to a separate inbox based on their contents. Of course this requires being able to scan an email and determine whether it is spam or ham, a classification problem. This is the subject of this assignment.

This assignment has two parts. Each part is worth 50% of the overall grade for this assignment.

For part one you will write a supervised learning based classifier to determine whether a given email is spam or ham. You must write and submit the code in this notebook. The training data is provided for you. You may use any classification method. Marks will be awarded primarily based on the accuracy of your classifier on unseen test data, but there are also marks for estimating how accurate you think your classifier will be.

In part two you will produce a short video explaining your implementation, any decisions or extensions you made, and what parameter values you used. This part is explained in more detail on the assignment page. The video file must be submitted with your assignment.

### Choice of Algorithm
While the classification method is a completely free choice, the assignment folder includes [a separate notebook file](data/naivebayes.ipynb) which can help you implement a Naïve Bayes solution. If you do use this notebook, you are still responsible for porting your code into *this* notebook for submission. A good implementation should give a high  enough accuracy to get a good grade on this section (50-70%).

You could also consider a k-nearest neighbour algorithm, but this may be less accurate. Logistic regression is another option that you may wish to consider.

If you are looking to go beyond the scope of the unit, you might be interested in building something more advanced, like an artificial neural network. This is possible just using `numpy`, but will require significant self-directed learning. *Extensions like this are left unguided and are not factored into the unit workload estimates.*

**Note:** you may use helper functions in libraries like `numpy` or `scipy`, but you **must not** import code which builds entire models for you. This includes but is not limited to use of libraries like `scikit-learn`, `tensorflow`, or `pytorch` – there will be plenty of opportunities for these libraries in later units. The point of this assignment is to understand code the actual algorithm yourself. ***If you are in any doubt about any particular library or function please ask a tutor.*** Submissions which ignore this will receive penalties or even zero marks.

If you choose to implement more than one algorithm, please feel free to include your code and talk about it in part two (your video presentation), but only the code in this notebook will be used in the automated testing.

## Training Data
The training data is described below and has 1000 rows. There is also a 500 row set of test data. These are functionally identical to the training data, they are just in a separate csv file to encourage you to split out your training and test data. You should consider how to best make use of all available data without overfitting, and to help produce an unbiased estimate for your classifier's accuracy.

The cell below loads the training data into a variable called `training_spam`.

In [2]:
import numpy as np

training_spam = np.loadtxt(open("data/training_spam.csv"), delimiter=",").astype(np.int)
print("Shape of the spam training data set:", training_spam.shape)
print(training_spam)

Shape of the spam training data set: (1000, 55)
[[1 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [1 1 1 ... 1 1 0]
 [1 0 0 ... 1 1 1]]


Your training set consists of 1000 rows and 55 columns. Each row corresponds to one email message. The first column is the _response_ variable and describes whether a message is spam `1` or ham `0`. The remaining 54 columns are _features_ that you will use to build a classifier. These features correspond to 54 different keywords (such as "money", "free", and "receive") and special characters (such as ":", "!", and "$"). A feature has the value `1` if the keyword appears in the message and `0` otherwise.

As mentioned there is also a 500 row set of *test data*. It contains the same 55 columns.

In [3]:
testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)
print("Shape of the spam testing data set:", testing_spam.shape)
print(testing_spam)

Shape of the spam testing data set: (500, 55)
[[1 0 0 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]


## Part One
Write all of the code for your classifier below this cell. There is some very rough skeleton code in the cell directly below. You may insert more cells below this if you wish, but you must not duplicate any cells as this can break the grading script.

### Submission Requirements
Your code must provide a variable with the name `classifier`. This object must have a method called `predict` which takes input data and returns class predictions. The input will be a single $n \times 54$ numpy array, your classifier should return a numpy array of length $n$ with classifications. There is a demo in the cell below, and a test you can run before submitting to check your code is working correctly.

Your code must run on our test machine in under 30 seconds. If you wish to train a more complicated model (e.g. neural network) which will take longer, you are welcome to save the model's weights as a file and then load these in the cell below so we can test it. You must include the code which computes the original weights, but this must not run when we run the notebook – comment out the code which actually executes the routine and make sure it is clear what we need to change to get it to run. Remember that we will be testing your final classifier on additional hidden data.

In [4]:
import pandas as pd
import pickle

"""To train the model from scratch see comment in the create_classifier() function."""


def get_kernel_matrix(x1, x2, sigma):
    """Function for the gram matrix used in the Kernel trick"""
    num_samples_x1 = x1.shape[0]
    num_samples_x2 = x2.shape[0]
    kernel_matrix = np.zeros([num_samples_x1, num_samples_x2])
    for nrow in range(num_samples_x1):
        for ncol in range(num_samples_x2):
            kernel_matrix[nrow][ncol] = np.exp(- sigma*(np.dot(x1[nrow]-x2[ncol], x1[nrow]-x2[ncol])))
    return kernel_matrix


class SVMSpamClassifier:
    """Support Vector Machine Classifier for spam email"""
    def __init__(self, sigma, C, train=False):
        self.sigma = sigma
        self.C = C
        self.save_weights = train
        # Load presaved weights if train set to False
        if train is False:
            self.support_x, self.support_y, self.support_lamb, self.param_b = self.load_data()
        else:
            self.support_ind = None
            self.support_x = None
            self.support_y = None
            self.support_lamb = None
            self.lamb = None
            self.param_b = None
            self.count = 0
            self.objective_func = -np.Inf
        
    
    def predict(self, x):
        """Function for classifying unseen data"""
        K = get_kernel_matrix(self.support_x, x, self.sigma)
        pred_y = []
        for i in range(x.shape[0]):
            z = np.dot(self.support_lamb * self.support_y, K[:,i]) +  self.param_b  
            if z < 0:
                z = -1
            else:
                z = 1
            pred_y.append(z)
        if self.train is True:
            return np.array(pred_y)
        else:
            return np.array([x if x == 1 else 0 for x in pred_y])
        
        
    def train(self, x, y, max_iter=1E6, epsilon=1E-4):
        """Function for training the SVM"""
        num_samples = x.shape[0]
        """Initialization and solve dual problem with SMO"""
        K = get_kernel_matrix(x, x, self.sigma)
        C = self.C
        self.lamb = np.zeros(num_samples)
        self.param_b = np.random.normal()
        #SMO algorithm
        while True:
            # Randomly select a pair (a, b) to optimize
            [a, b] = np.random.choice(num_samples, 2, replace=False)
            if K[a, a] + K[b, b] - 2 * K[a,b] == 0:
                continue
                
            lamb_a_old, lamb_b_old = self.lamb[a], self.lamb[b]
            Ea =  np.dot(self.lamb * y, K[:,a]) + self.param_b - y[a]
            Eb =  np.dot(self.lamb * y, K[:,b]) + self.param_b - y[b]
            lamb_a_new_unclip = lamb_a_old + y[a] *(Eb - Ea)/(K[a,a] + K[b,b] - 2 * K[a, b])
            xi = - lamb_a_old * y[a] - lamb_b_old * y[b]
            
            if y[a] != y[b]:
                L = max(xi * y[b], 0)
                H = min(C + xi * y[b], C)
            else:
                L = max(0, -C - xi * y[b])
                H = min(C, -xi * y[b])
                
            if lamb_a_new_unclip < L:
                lamb_a_new = L
            elif lamb_a_new_unclip > H:
                lamb_a_new = H
            else:
                lamb_a_new = lamb_a_new_unclip
                
            lamb_b_new = lamb_b_old + (lamb_a_old - lamb_a_new) * y[a] * y[b]
            if lamb_a_new > 0 and lamb_a_new < C:
                self.param_b =  self.param_b - Ea + (lamb_a_old - lamb_a_new) * y[a] * K[a,a] + (lamb_b_old - lamb_b_new) * y[b] * K[b,a]
            elif lamb_b_new > 0 and lamb_b_new < C:
                self.param_b = self.param_b - Eb + (lamb_a_old - lamb_a_new) * y[a] * K[a,b] + (lamb_b_old - lamb_b_new) * y[b] * K[b,b]
            self.lamb[a], self.lamb[b] = lamb_a_new, lamb_b_new
            
            self.count += 1
            local_count += 1

            # Determine whether to stop training
            if local_count >= max_iter or self.count % 10000 ==0:
                self.support_ind =  self.lamb > 0
                self.support_x = x[self.support_ind]
                self.support_y = y[self.support_ind]
                self.support_lamb = self.lamb[self.support_ind]	
                support_K = K[self.support_ind, :][:, self.support_ind]
                new_objective_func = np.sum(self.support_lamb) - 0.5 * np.dot(np.matmul((self.support_lamb * self.support_y).T, support_K).T, self.support_lamb * self.support_y) 
                
                # If the change of dual objective function is less than epsilon stop training
                if abs(new_objective_func - self.objective_func) <= epsilon:
                    break
                else:
                    self.objective_func = new_objective_func
                if local_count >= max_iter:
                    break
                    
        # If True will save weights to be used again            
        if self.save_weights:
            self.save_data()
    

    def save_data(self):
        """Function for saving data to be used later"""
        with open('support_x.pkl', 'wb') as f:
            pickle.dump(self.support_x, f)  
        with open('support_y.pkl', 'wb') as f:
            pickle.dump(self.support_y, f)
        with open('support_lamb.pkl', 'wb') as f:
            pickle.dump(self.support_lamb, f)
        with open('param_b.pkl', 'wb') as f:
            pickle.dump(self.param_b, f)
            
            
    def load_data(self):
        """Function for loading data when initialising classifier"""
        with open('support_x.pkl', 'rb') as f:
            support_x = pickle.load(f)
        with open('support_y.pkl', 'rb') as f:
            support_y = pickle.load(f)
        with open('support_lamb.pkl', 'rb') as f:
            support_lamb = pickle.load(f)
        with open('param_b.pkl', 'rb') as f:
            param_b = pickle.load(f)
        return support_x, support_y, support_lamb, param_b 
    
    
def create_classifier():
    """To train the model from scratch set train to True"""
    classifier = SVMSpamClassifier(0.01, 100, train=False)
    return classifier

classifier = create_classifier()

### Accuracy Estimate
In the cell below there is a function called `my_accuracy_estimate()` which returns `0.5`. Before you submit the assignment, write your best guess for the accuracy of your classifier into this function, as a percentage between `0` and `1`. So if you think you will get 80% of inputs correct, return the value `0.8`. This will form a small part of the marking criteria for the assignment, to encourage you to test your own code.

In [5]:
def my_accuracy_estimate():
    return 0.92

Write all of the code for your classifier above this cell.

### Testing Details
Your classifier will be tested against some hidden data from the same source as the original. The accuracy (percentage of classifications correct) will be calculated, then benchmarked against common methods. At the very high end of the grading scale, your accuracy will also be compared to the best submissions from other students (in your own cohort and others!). Your estimate from the cell above will also factor in, and you will be rewarded for being close to your actual accuracy (overestimates and underestimates will be treated the same).

#### Test Cell
The following code will run your classifier against the provided test data. To enable it, set the constant `SKIP_TESTS` to `False`.

The original skeleton code above classifies every row as ham, but once you have written your own classifier you can run this cell again to test it. So long as your code sets up a variable called `classifier` with a method called `predict`, the test code will be able to run. 

Of course you may wish to test your classifier in additional ways, but you *must* ensure this version still runs before submitting.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [9]:
SKIP_TESTS = False

if not SKIP_TESTS:
    testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)
    test_data = testing_spam[:, 1:]
    test_labels = testing_spam[:, 0]

    predictions = classifier.predict(test_data)
    accuracy = np.count_nonzero(predictions == test_labels)/test_labels.shape[0]
    print(f"Accuracy on test data is: {accuracy}")

Accuracy on test data is: 0.922


In [7]:
import sys
import pathlib

fail = False;

if not SKIP_TESTS:
    fail = True;
    print("You must set the SKIP_TESTS constant to True in the cell above.")
    
p3 = pathlib.Path('./spamclassifier.ipynb')
if not p3.is_file():
    fail = True
    print("This notebook file must be named spamclassifier.ipynb")
    
if "create_classifier" not in dir():
    fail = True;
    print("You must include a function called create_classifier.")

if "my_accuracy_estimate" not in dir():
    fail = True;
    print("You must include a function called my_accuracy_estimate.")
else:
    if my_accuracy_estimate() == 0.5:
        print("Warning:")
        print("You do not seem to have provided an accuracy estimate, it is set to 0.5.")
        print("This is the actually the worst possible accuracy – if your classifier")
        print("got 0.1 then it could invert its results to get 0.9!")
    
print("INFO: Make sure you follow the instructions on the assignment page to submit your video.")
print("Failing to include this could result in an overall grade of zero for both parts.")
print()

if fail:
    sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
else:
    print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
    print("assignment page, without changing any filenames.")
    print()
    print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")

INFO: Make sure you follow the instructions on the assignment page to submit your video.
Failing to include this could result in an overall grade of zero for both parts.

All checks passed. When you are ready to submit, upload the notebook and readme file to the
assignment page, without changing any filenames.

If you need to submit multiple files, you can archive them in a .zip file. (No other format.)


In [8]:
# This is a test cell. Please do not modify or delete.